import {useCallback,useEffect,useMemo,useState} from "react";
import {createApiClient,uploadArtifact} from "./api/client.js";
import WorkflowBuilder from "./WorkflowBuilder.js";
type Project={id:string;slug:string;name:string};
type Compound={id:string;accession:string;name:string;inchikey:string;payload:{parent?:{canonical_smiles?:string}}};
type Snapshot={project_id:string;run_id:string;status:string;submission?:{error?:string|null};tasks?:Array<{task_id:string;stage_id:string;state:string}>};
type Lineage={artifacts?:Array<{id:string;media_type:string;kind:string;size_bytes:number;sha256:string}>};
const template=JSON.stringify({schema:"caddsuite.workflow/1",name:"New workflow",inputs:{},stages:[],outputs:{}},null,2);
function ulid(){const a="0123456789ABCDEFGHJKMNPQRSTVWXYZ";let random=0n;for(const b of crypto.getRandomValues(new Uint8Array(10)))random=(random<<8n)|BigInt(b);let v=(BigInt(Date.now())<<80n)|random;let s="";for(let i=0;i<26;i++){s=a[Number(v&31n)]+s;v>>=5n}return s}
async function get<T>(p:Promise<{data?:T;error?:unknown;response:Response}>):Promise<T>{const r=await p;if(!r.response.ok){const d=r.error as {detail?:string}|undefined;throw Error(d?.detail||await r.response.text()||"Request failed")}if(r.data===undefined)throw Error("API returned no body");return r.data}
export default function App(){
const[url,setUrl]=useState("http://127.0.0.1:8000"),[token,setToken]=useState(""),[ok,setOk]=useState(false),[projects,setProjects]=useState<Project[]>([]),[pid,setPid]=useState(""),[compounds,setCompounds]=useState<Compound[]>([]),[caps,setCaps]=useState<Record<string,unknown>[]>([]),[name,setName]=useState(""),[slug,setSlug]=useState(""),[smi,setSmi]=useState(""),[cname,setCname]=useState(""),[wf,setWf]=useState(template),[inputs,setInputs]=useState("{}"),[plan,setPlan]=useState<unknown>(null),[run,setRun]=useState<Snapshot|null>(null),[rid,setRid]=useState(""),[lineData,setLineData]=useState<Lineage|null>(null),[logText,setLogText]=useState(""),[err,setErr]=useState(""),[msg,setMsg]=useState(""),[file,setFile]=useState<File|null>(null);
const api=useMemo(()=>createApiClient(url,token),[url,token]),project=projects.find(x=>x.id===pid);
const refresh=useCallback(async(id:string)=>{const r=await api.GET("/v1/projects/{project_id}/compounds",{params:{path:{project_id:id}}});if(!r.response.ok)throw Error("Unable to load compound registry");setCompounds((r.data||[]) as Compound[])},[api]);
async function connect(){try{setErr("");const[p,c]=await Promise.all([get(api.GET("/v1/projects")),get(api.GET("/v1/workflows/capabilities"))]);setProjects(p as Project[]);setCaps(((c as {capabilities?:Record<string,unknown>[]}).capabilities)||[]);setOk(true);if(!pid&&(p as Project[]).length)setPid((p as Project[])[0].id);setMsg("Connected to CADD Suite API")}catch(e){setOk(false);setErr(String(e))}}
useEffect(()=>{if(ok&&pid)void refresh(pid).catch(e=>setErr(String(e)));else setCompounds([])},[ok,pid,refresh]);
async function createProject(e:React.FormEvent){e.preventDefault();try{const p=await get(api.POST("/v1/projects",{body:{slug,name}})) as Project;setProjects(x=>[...x,p]);setPid(p.id);setName("");setSlug("");setMsg("Project created: "+p.slug)}catch(x){setErr(String(x))}}
async function addCompound(e:React.FormEvent){e.preventDefault();try{const r=await get(api.POST("/v1/projects/{project_id}/compounds",{params:{path:{project_id:pid}},body:{smiles:smi,name:cname}})) as unknown as {compound:{accession:string};created:boolean};await refresh(pid);setMsg((r.created?"Registered ":"Matched existing identity ")+r.compound.accession+"; raw input retained");setSmi("");setCname("")}catch(x){setErr(String(x))}}
async function planWorkflow(){try{setPlan(await get(api.POST("/v1/workflows/plan",{body:JSON.parse(wf) as never})));setErr("");setMsg("Workflow compiled against installed capabilities")}catch(x){setPlan(null);setErr(String(x))}}
async function submit(){try{const id=ulid();const r=await get(api.POST("/v1/projects/{project_id}/runs/{run_id}/execute",{params:{path:{project_id:pid,run_id:id}},body:{workflow:JSON.parse(wf) as never,inputs:JSON.parse(inputs)}}));setRid(id);setRun(r as Snapshot);setMsg("Workflow queued")}catch(x){setErr(String(x))}}
const poll=useCallback(async()=>{if(!pid||!rid)return;try{setRun(await get(api.GET("/v1/projects/{project_id}/runs/{run_id}/status",{params:{path:{project_id:pid,run_id:rid}}})) as Snapshot)}catch(e){setErr(String(e))}},[api,pid,rid]);
useEffect(()=>{if(!ok||!rid)return;void poll();const t=setInterval(()=>void poll(),2500);return()=>clearInterval(t)},[ok,rid,poll]);
async function cancel(){try{await get(api.POST("/v1/projects/{project_id}/runs/{run_id}/cancel",{params:{path:{project_id:pid,run_id:rid}}}));setMsg("Cancellation requested")}catch(e){setErr(String(e))}}
function insertCompounds(){try{const x=JSON.parse(inputs),key=Object.keys(x).find(k=>k.toLowerCase().includes("compound"));if(!key)throw Error("Workflow needs a compound input declaration");if(!compounds.length)throw Error("Register compounds first");x[key]=compounds.map(c=>c.payload);setInputs(JSON.stringify(x,null,2));setMsg("Inserted compounds into "+key)}catch(e){setErr(String(e))}}
async function upload(){if(!file)return;try{const r=await uploadArtifact(url,token,pid,file,"input"),d=await r.json() as {artifact:{artifact_id:string;role:string;sha256:string}};setMsg("Uploaded to project CAS. Artifact ID: "+d.artifact.artifact_id+"; SHA-256: "+d.artifact.sha256)}catch(e){setErr(String(e))}}
async function readLog(id:string){try{const r=await fetch(url.replace(/\/$/,"")+"/v1/projects/"+pid+"/artifacts/"+id+"/text?tail_bytes=65536",{headers:{Authorization:"Bearer "+token}});if(!r.ok)throw Error(await r.text());setLogText(await r.text())}catch(e){setErr(String(e))}}
async function lineage(){try{const r=await fetch(url.replace(/\/$/,"")+"/v1/provenance/runs/"+rid,{headers:{Authorization:"Bearer "+token}});if(!r.ok)throw Error(await r.text());setLineData(await r.json() as Lineage);setLogText("");setMsg("Run provenance loaded")}catch(e){setErr(String(e))}}
return <div className="shell"><header><div className="brand"><b className="mark">C</b><span>CADD <strong>SUITE</strong><small>COMPUTATIONAL DISCOVERY WORKSPACE</small></span></div><div className="headright"><span className={ok?"online":""}>API {ok?"CONNECTED":"NOT CONNECTED"}</span><button className="dark" onClick={()=>void connect()}>{ok?"Refresh API":"Connect API"}</button></div></header>
<main><section className="hero"><div><small>LOCAL RESEARCH ENVIRONMENT</small><h1>Make every result<br/><i>traceable.</i></h1><p>Build and monitor computational chemistry workflows with explicit inputs, engine capabilities, and scientific provenance.</p></div><b className="folio">WORKFLOW / 01</b></section>
<section className="panel connection"><h2>01 / Connect to your API</h2><div className="row"><label>API base URL<input value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Access token<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Local API bearer token"/></label></div>{err&&<div className="alert">{err}</div>}{msg&&!msg.startsWith("{")&&<div className="success">{msg}</div>}</section>
<div className="columns"><aside><section className="panel"><h2>02 / Project</h2><select disabled={!ok} value={pid} onChange={e=>setPid(e.target.value)}><option value="">Choose project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} - {p.slug}</option>)}</select>{project&&<code className="id">{project.id}</code>}<form onSubmit={e=>void createProject(e)}><h3>Create project</h3><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Project name"/><input required pattern="[a-z0-9][a-z0-9-]{0,62}" value={slug} onChange={e=>setSlug(e.target.value)} placeholder="lowercase-project-slug"/><button className="light" disabled={!ok}>Create project</button></form></section>
<section className="panel"><h2>03 / Compound registry <span className="pill">{compounds.length}</span></h2><p>SMILES are standardized into parent identities; submissions remain linked for provenance.</p><form onSubmit={e=>void addCompound(e)}><input required value={cname} onChange={e=>setCname(e.target.value)} placeholder="Compound name"/><input required value={smi} onChange={e=>setSmi(e.target.value)} placeholder="SMILES (example: CCO)"/><button className="light" disabled={!ok||!pid}>Standardize and register</button></form><div className="list">{compounds.map(c=><div className="compound" key={c.id}><b>{c.accession}</b><span>{c.name}<small>{c.payload.parent?.canonical_smiles||c.inchikey}</small></span></div>)}{!compounds.length&&<p className="empty">Registered compounds appear here.</p>}</div></section></aside>
<div className="stack"><section className="panel"><div className="between"><h2>04 / Workflow designer</h2><span className="form-badge">CAPABILITY-DRIVEN STAGE FORMS</span></div><div className="toolbar">CAPABILITY DISCOVERY <span>{caps.length} installed stages</span></div><details><summary>Installed stage capabilities</summary><div className="chips">{caps.map((c,i)=><span key={i}>{String(c.kind||c.stage_kind||"stage")} / {String(c.engine||"generic")}</span>)}</div></details><label className="editorlabel">WORKFLOW DEFINITION <span>caddsuite.workflow/1 / engine-neutral DAG</span></label><WorkflowBuilder capabilities={caps} onChange={setWf}/><details className="advanced-workflow"><summary>Advanced workflow JSON</summary><textarea className="editor" value={wf} onChange={e=>setWf(e.target.value)} spellCheck={false}/></details><div className="actions"><button className="outline" disabled={!ok} onClick={()=>void planWorkflow()}>Validate and plan</button><button className="dark" disabled={!ok||!pid} onClick={()=>void submit()}>Queue workflow</button></div>{plan!==null&&<pre className="result">{JSON.stringify(plan,null,2)}</pre>}</section>
<section className="panel"><div className="between"><h2>05 / Workflow inputs</h2><button className="link" disabled={!compounds.length} onClick={insertCompounds}>Insert registered compounds</button></div><p>Provide normalized contracts declared in the workflow definition.</p><label className="editorlabel">INPUT CONTRACTS <span>JSON / validated before execution</span></label><textarea className="editor inputs" value={inputs} onChange={e=>setInputs(e.target.value)} spellCheck={false}/><div className="upload"><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="light" disabled={!ok||!pid||!file} onClick={()=>void upload()}>Upload artifact to project</button></div></section>
<section className="panel"><div className="between"><h2>06 / Run monitor</h2>{run&&<span className="pill">{run.status}</span>}</div>{!run&&<p className="empty">Submitted workflows and task progress appear here.</p>}{run&&<><div className="runmeta"><span>RUN ID <code>{rid}</code></span><button className="outline" onClick={()=>void cancel()} disabled={["succeeded","failed","stopped","cancelled"].includes(run.status)}>Cancel run</button></div>{(run.tasks||[]).map(t=><div className="task" key={t.task_id}><i className={"dot "+t.state}/><b>{t.stage_id}</b><span>{t.state}</span><code>{t.task_id.slice(0,10)}</code></div>)}{run.submission?.error&&<div className="alert">{run.submission.error}</div>}<div className="end"><button className="link" onClick={()=>void lineage()}>Inspect run provenance</button></div>{lineData&&<div className="lineage"><h3>Run artifacts</h3>{(lineData.artifacts||[]).map(a=><div className="artifact" key={a.id}><span>{a.kind+" / "+a.media_type+" / "+a.size_bytes+" B"}</span><code>{a.id}</code>{a.media_type==="text/plain"&&<button className="link" onClick={()=>void readLog(a.id)}>Read log tail</button>}</div>)}{logText&&<pre className="logtext">{logText}</pre>}</div>}</>}</section></div></div>
<footer><b>CADD SUITE / COMPUTATIONAL RESULTS ARE PREDICTIONS</b><span>Scientific predictions require suitable validation and experimental follow-up.</span></footer></main></div>}
