"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-09-23 05:56:25.920957

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('software_agents',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('license_class', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', 'kind')
    )
    op.create_table('accession_counters',
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'kind', 'scope')
    )
    op.create_table('compounds',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('accession', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('inchikey', sa.String(length=27), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'accession')
    )
    with op.batch_alter_table('compounds', schema=None) as batch_op:
        batch_op.create_index('ix_compounds_project_inchikey', ['project_id', 'inchikey'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('accession', sa.String(length=32), nullable=False),
    sa.Column('workflow_hash', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'accession')
    )
    op.create_table('compound_forms',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('compound_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('smiles', sa.Text(), nullable=False),
    sa.Column('formal_charge', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compound_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compound_forms_compound_id'), ['compound_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('run_id', sa.String(length=26), nullable=False),
    sa.Column('stage_id', sa.String(length=64), nullable=False),
    sa.Column('subject_kind', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.String(length=26), nullable=True),
    sa.Column('cache_key', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_cache_key'), ['cache_key'], unique=False)
        batch_op.create_index('ix_tasks_run_stage', ['run_id', 'stage_id'], unique=False)

    op.create_table('task_attempts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('task_id', sa.String(length=26), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('executor', sa.String(length=32), nullable=False),
    sa.Column('host', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('platform', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_status', sa.String(length=32), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'attempt_no')
    )
    op.create_table('validation_issues',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('subject_kind', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('task_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_issues_code'), ['code'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('producer_attempt_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['producer_attempt_id'], ['task_attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('attempt_agents',
    sa.Column('attempt_id', sa.String(length=26), nullable=False),
    sa.Column('agent_id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['software_agents.id'], ),
    sa.ForeignKeyConstraint(['attempt_id'], ['task_attempts.id'], ),
    sa.PrimaryKeyConstraint('attempt_id', 'agent_id', 'role')
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('issue_id', sa.String(length=26), nullable=True),
    sa.Column('task_id', sa.String(length=26), nullable=True),
    sa.Column('chosen_key', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['validation_issues.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('project_id', sa.String(length=26), nullable=False),
    sa.Column('contract', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('subject_kind', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.String(length=26), nullable=True),
    sa.Column('accession', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('primary_value', sa.Float(), nullable=True),
    sa.Column('primary_unit', sa.String(length=32), nullable=True),
    sa.Column('attempt_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['task_attempts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index('ix_results_project_contract', ['project_id', 'contract'], unique=False)
        batch_op.create_index('ix_results_subject', ['subject_id'], unique=False)

    op.create_table('attempt_artifacts',
    sa.Column('attempt_id', sa.String(length=26), nullable=False),
    sa.Column('artifact_id', sa.String(length=26), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['attempt_id'], ['task_attempts.id'], ),
    sa.PrimaryKeyConstraint('attempt_id', 'artifact_id', 'direction', 'role')
    )
    op.create_table('software_environments',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('lock_sha256', sa.String(length=64), nullable=False),
    sa.Column('lock_artifact_id', sa.String(length=26), nullable=True),
    sa.Column('key_packages', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lock_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix', 'lock_sha256')
    )
    with op.batch_alter_table('software_environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_software_environments_lock_sha256'), ['lock_sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_software_environments_lock_sha256'))

    op.drop_table('software_environments')
    op.drop_table('attempt_artifacts')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index('ix_results_subject')
        batch_op.drop_index('ix_results_project_contract')

    op.drop_table('results')
    op.drop_table('decisions')
    op.drop_table('attempt_agents')
    op.drop_table('artifacts')
    with op.batch_alter_table('validation_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_issues_code'))

    op.drop_table('validation_issues')
    op.drop_table('task_attempts')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_run_stage')
        batch_op.drop_index(batch_op.f('ix_tasks_cache_key'))

    op.drop_table('tasks')
    with op.batch_alter_table('compound_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compound_forms_compound_id'))

    op.drop_table('compound_forms')
    op.drop_table('workflow_runs')
    with op.batch_alter_table('compounds', schema=None) as batch_op:
        batch_op.drop_index('ix_compounds_project_inchikey')

    op.drop_table('compounds')
    op.drop_table('accession_counters')
    op.drop_table('software_agents')
    op.drop_table('projects')
    # ### end Alembic commands ###
